# Generated by Django 2.0.7 on 2018-07-29 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0001_initial'),
        ('buildings', '0001_initial'),
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlockRoomEntryRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.Flock')),
                ('room_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buildings.AnimalRoomEntry')),
            ],
        ),
        migrations.CreateModel(
            name='FlockRoomExitRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.Flock')),
                ('room_exit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buildings.AnimalRoomExit')),
            ],
        ),
    ]
